name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Basic Compiling Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: make
      run: make -j
